### ISSUE TITLE
Not authorized to get the contact

### ISSUE THREAD

**Issue by demurgos** [ocilo/skype-http#20]
A change in the Skype API caused a regression in the library. The library is no longer able to fetch the contact data. This can be seen by running the example. We get a large number of errors of the following form:

```
{ statusCode: 403,
  body: '{"status":{"code":40300,"text":"User \'<local-username>\' is not authorized to request resource of user \'<contact-username>\'"}}',
  headers: 
   { server: 'nginx/1.7.8',
     date: 'Tue, 09 May 2017 19:29:31 GMT',
     'content-type': 'application/json; ver=1.0; charset=utf-8',
     'content-length': '118',
     connection: 'close',
     'x-stratus-processing-time': '0.0188',
     'x-skype-request-id': '7ee0275d',
     'x-stratus-request-id': '7ee0275d',
     'cache-control': 'no-cache, must-revalidate, stratus-cache-per-request=true',
     'x-frame-options': 'SAMEORIGIN',
     'x-content-type-options': 'nosniff',
     'x-xss-protection': '1; mode=block',
     'strict-transport-security': 'max-age=31536000; includeSubdomains;' } }
{ net: Unable to fetch contact
    at Object.<anonymous> (/data/projects/various/skype-http/build/example/lib/api/get-contact.js:33:35)
    at Generator.next (<anonymous>)
    at fulfilled (/data/projects/various/skype-http/build/example/lib/api/get-contact.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7) name: 'net', data: {} }

```

**Comment by mitchcapper** [comment]
I can look into this if you prefer.

**Comment by demurgos** [comment]
Ok, I cannot assign this issue to you but you can work on this.

The `getContact` function is defined in [`src/api/get-contact.ts`](https://github.com/ocilo/skype-http/blob/master/src/lib/api/get-contact.ts). It seems that I already was looking into this (since there are some unconditional `console.log`) but it was a few months ago so I no longer remember the issue.
I know that Skype has multiple domains. Currently it seems that `getContact` uses the `/users/username` route from the API (something like `https://api.aps.skype.com/v1/`) ([defined here](https://github.com/ocilo/skype-http/blob/master/src/lib/api-uri.ts#L104)). I know that there is also a `contacts.skype.com` subdomain, I even started to [define the available routes](https://github.com/ocilo/skype-http/blob/master/src/lib/contacts-uri.ts).

I think you'll either need to add a token or cookie for the route or switch to the `contacts` subdomain.

**Comment by mitchcapper** [comment]
Alright after reading the code and what I can find online I then tested with SkPy which has the same issue (unauthorized for users) and is using the same url we are.  If this action is used by the real client I can check the network for that to see how it does it.

**Comment by demurgos** [comment]
Ok, I also tend to check with SkPy or watch the network. I do not see any issue about this on the SkPy repo, it may be worth opening one? It should also mean that it was caused by a recent change.
You can effectively inspect the network requests (it's one of methods I use).

**Comment by mitchcapper** [comment]
Opened bug with SkPy will use the web client and do some tracing to try and investigate further.

**Comment by OllieTerrance** [comment]
Until I get a chance to look into this, the [Skype Pidgin plugin](https://github.com/EionRobb/skype4pidgin) is also a good reference.  Unsure if that's affected or not though.

**Comment by mitchcapper** [comment]
I checked out what they do, they call the full contacts URL and then pass the user names to only retrieve those users.   I am not sure if this provides any less data than the old getContact url but I think this seems like a good solution.  

their getContact calls their getContacts function with just that contact as the only one:
https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/skypeweb_contacts.c#L1067

Assuming you agree will make a PR.

**Comment by demurgos** [comment]
Well, it seems that the web client does try to retrieve a single contact but always uses an array.
It seems that the real client uses the `contacts.skype.com` subdomain.

In fact, I just checked the git history, and `getContact` was previously implemented with `GET https://contacts.skype.com/contacts/v1/users/{username}/contacts/{contact}`. If I remember, I changed it because it returned less information or stopped working.

Here are the 3 other ways to retrieve the contacts that I am aware of:

- `GET https://contacts.skype.com/contacts/v1/users/:user/contacts/profiles`
  Used by pidgin (Just to clarify: I think they do a single call)
  - Request headers: Nothing special, requires `X-Skypetoken`
  - Query string
    - `contacts`: array of usernames (prefixed or not by `8:` etc. ?)
  - Response: not sure, maybe the same as the next method?

- `GET https://contacts.skype.com/contacts/v2/users/<myusername>?delta&reason=default`
  Used by the real web client to get all the contacts
  - Request headers: Nothing special, requires `X-Skypetoken`
  - Query string
    - `delta` (empty string / flag)
    - `reason`: `"default"`

  - Response (JSON)
    ```json
    {
      "contacts": [
        {
          "person_id": "101b7032-0000-0000-0000-000000000000",
          "mri": "8:user1",
          "display_name": "User1Name",
          "display_name_source": "profile",
          "profile": {
            "avatar_url": "https://avatar.skype.com/v1/avatars/user1?auth_key=1278046225",
            "birthday": "1986-07-12",
            "gender": "male",
            "locations": [
              {
                "type": "home",
                "country": "FR",
                "city": "Redacted City",
                "state": "Redacted State"
              }
            ],
            "name": {
              "first": "User1First",
              "nickname": "User1Nickname"
            },
            "language": "fr"
          },
          "authorized": true,
          "auth_certificate": "Redacted (base64)",
          "blocked": false,
          "creation_time": "2015-03-19T06:34:42.74Z"
        },
        {
          "person_id": "024fad32-0000-0000-0000-000000000000",
          "mri": "8:user2",
          "display_name": "User2Name",
          "display_name_source": "profile",
          "profile": {
            "avatar_url": "https://avatar.skype.com/v1/avatars/user2?auth_key=-139597677",
            "birthday": "1992-10-03",
            "gender": "male",
            "locations": [
              {
                "type": "home",
                "country": "FR",
                "city": "Redacted city"
              }
            ],
            "mood": "Some redacted text",
            "name": {
              "first": "User2First",
              "nickname": "User2Nickname"
            },
            "language": "FR"
          },
          "authorized": true,
          "auth_certificate": "Base64 (524 chars)",
          "blocked": false,
          "creation_time": "2016-05-09T06:34:43.39Z"
        }
      ]
    }
    ```

- `POST https://api.skype.com/users/batch/profiles`
  Used by the real web client to get _some_ contacts (why just some contacts ?)
  - Request headers: Nothing special, requires `X-Skypetoken`
  - Request body (JSON)
    ```json
    {
      "usernames": ["username1", "username2", "username3"]
    }
    ```

  - Response (JSON)
    ```json
    [
      {
        "firstname": "Contact1 Firstname",
        "lastname": null,
        "birthday": "1950-01-01",
        "gender": "1",
        "language": "FR",
        "country": "FR",
        "province": null,
        "city": "Paris",
        "homepage": null,
        "about": null,
        "emails": [],
        "jobtitle": null,
        "phoneMobile": null,
        "phoneHome": null,
        "phoneOffice": null,
        "mood": null,
        "richMood": null,
        "avatarUrl": "https://api.skype.com/users/username1/profile/avatar",
        "namespace": null,
        "displayname": "Contact1 Displayname",
        "username": "username1"
      },
      {
        "firstname": "Contact2 Firstname",
        "lastname": null,
        "birthday": "1997-06-18",
        "gender": "1",
        "language": "fr",
        "country": "fr",
        "province": null,
        "city": "Some redacted city",
        "homepage": null,
        "about": null,
        "emails": [],
        "jobtitle": null,
        "phoneMobile": null,
        "phoneHome": null,
        "phoneOffice": null,
        "mood": null,
        "richMood": null,
        "avatarUrl": "https://api.skype.com/users/username2/profile/avatar",
        "namespace": null,
        "displayname": "Contact2 displayname",
        "username": "username2"
      },
      {
        "firstname": null,
        "lastname": null,
        "birthday": null,
        "gender": 0,
        "language": null,
        "country": null,
        "province": null,
        "city": null,
        "homepage": null,
        "about": null,
        "emails": [],
        "jobtitle": null,
        "phoneMobile": null,
        "phoneHome": null,
        "phoneOffice": null,
        "mood": null,
        "richMood": null,
        "avatarUrl": null,
        "namespace": null,
        "displayname": null,
        "username": "username3"
      }
    ]
    ```

There is also this call, but I do not know what it does:

- `POST https://client-s.gateway.messenger.live.com/v1/users/ME/contacts`
  - Request headers: `Registrationtoken` (no `X-Skypetoken`)
  - Request body (JSON)
    ```json
    {
      "contacts": [
        {
          "id": "8:user1"
        },
        {
          "id": "8:user2"
        },
        {
          "id": "8:user3"
        }
      ]
    }
    ```
  - Response (JSON)
    ```json
    {}
    ```

**Comment by OllieTerrance** [comment]
There's also `https://api.skype.com/users/self/contacts/profiles`, which retrieves public info for any user, not just a contact:

#### POST body
```
contacts[]: <user-id>
```
#### JSON response
```
[{'avatarUrl': null,
  'city': null,
  'country': null,
  'displayname': null,
  'firstname': '...',
  'lastname': '...',
  'mood': null,
  'richMood': null,
  'username': '<user-id>'}]
```

It looks like it's just the call to `https://api.skype.com/users/<user-id>/profile` that's affected.  Feels like `https://contacts.skype.com/contacts/v2/users/<user-id>` is the right one to use.

> `POST https://api.skype.com/users/batch/profiles`
> Used by the real web client to get some contacts (why just some contacts ?)

Recently contacted users?

**Comment by demurgos** [comment]
@OllieTerrance Thank you, it's the URL I had in mind for my first method but I messed up the base URL. It has effectively less data than the other responses.

I got a 401 error for `https://contacts.skype.com/contacts/v2/users/<user-id>`. I sent a `GET` request with `X-Skypetoken`. Do I need something more ?



> >   POST https://api.skype.com/users/batch/profiles
> >  Used by the real web client to get some contacts (why just some contacts ?)
>
> Recently contacted users?

I have 30 contacts on this account but it fetches only 6 of them after a few minutes (always the same, I restarted the client 2 times). They are 4 of them are rather inactive but 2 of them connect regularly.

**Comment by mitchcapper** [comment]
Is it a lack of details we don't want to follow the pidgin function (posting the contact array?)?

**Comment by demurgos** [comment]
> Feels like `https://contacts.skype.com/contacts/v2/users/<user-id>` is the right one to use.
Agreed, it seems that it's the one with the most data and since its marked as `v2`, it may be more stable.

@mitchcapper The endpoint used by Pidgin is the one described by @OllieTerrance (`POST https://api.skype.com/users/self/contacts/profiles` with the contacts array).

Here are the pros and cons the two endpoints in my opinion (I'll refer to them by their hostname): 
- `contacts.skype.com` is used by the official web client but not `api.skype.com` (upon a 30-minutes test)
- `api.skype.com` is used by Pidgin
- `contacts.skype.com` seems to provide more data than `api.skype.com`. (not sure ?)
- `api.skype.com` allows to filter by contact name with `contacts[]`, `contacts.skype.com` allows to filter by contact type with 'skype', 'msn', 'pstn', 'agent' or 'lync'
- We are already using `contacts.skype.com` to get all the contacts with `GET https://contacts.skype.com/contacts/v1/users/:username/contacts`

**Comment by OllieTerrance** [comment]
> `https://contacts.skype.com/contacts/v2/users/<user-id>`

Oh, that only does all contacts, doesn't it...  you request all contacts by using your own username, as you noted above.  (That is, it's a 401 for anyone but yourself.)

The way SkPy handles contacts is by requesting all contacts and caching them, then deferring to the single user endpoint on a cache miss, and the public info endpoint failing that.  The only time should get a contact cache miss (as opposed to a non-contact) is if they've been invited as a contact since the fetch.

**Comment by demurgos** [comment]
> The way SkPy handles contacts is by requesting all contacts and caching them, then deferring to the single user endpoint on a cache miss, and the public info endpoint failing that.

The issue is that the _single-user_ endpoint we used (`GET https://api.skype.com/users/<contact-id>/profile`) no longer works. According to [the issue opened on SkPy](https://github.com/OllieTerrance/SkPy/issues/61) you are using the same single-user endpoint (https://github.com/OllieTerrance/SkPy/blob/master/skpy/user.py#L394), do you confirm it?

The problem is to chose a replacement for the single-user endpoint. Caching is a possible solution, but it may be interesting to find a way that matches the previous behaviour the best (currently it would be `POST https://api.skype.com/users/self/contacts/profiles` with `contacts` containin a single username, but is it really worth having a dedicated function for a single user if it is no longer provided by the skype API?).

**Comment by OllieTerrance** [comment]
Indeed, `POST https://api.skype.com/users/batch/profiles` looks like the only supported option now.

I'm just seeing which fields are actually returned from each...

**Comment by demurgos** [comment]
I think that I found a confirmation that `POST https://api.skype.com/users/batch/profiles` with `usernames[]` set to a single item is the official way to retrieve the data for a single user. This is the request sent to the server when you search for a new contact and then select one of the results. Skype sends the request when you open the conversation window with this unknown contact.

I'd still like to better understand the difference between Skype's `POST https://api.skype.com/users/batch/profiles` and Pidgin's `POST https://api.skype.com/users/self/contacts/profiles`.

**Comment by OllieTerrance** [comment]
I think Skype for Web used to use `https://api.skype.com/users/self/contacts/profiles` a while back (presumably where the Pidgin plugin first caught wind of it), so maybe it's just been replaced...

Also, if you take a look at the return format for [`GET https://api.skype.com/users/<user-id>/profile`](https://skpy.t.allofti.me/protocol/contact.html#get-https---api.skype.com-users-(string-id)-profile), it appears to use all the same field names as `POST https://api.skype.com/users/batch/profiles`.

**Comment by demurgos** [comment]
Ok, thank you for confirming that it returns the same resources.

@mitchcapper How about implementing it with batch then ? Do you want to do the PR ? I was able to check that it works (with `form: {usernames: [contactId]}`) but it requires a bit of clean up (removing the debug logs).

**Comment by mitchcapper** [comment]
Happy to do that PR, if you dump the search traffic method we could also look at adding a proper search for other contacts.

**Comment by mitchcapper** [comment]
Even though @OllieTerrance nice table showed it,  I do not seem to see prefix's on the `username` field from the batch command (and searching for a user who is not a skype/type 8 user seems to also return not found to batch).   Not a big deal, we can assume users returned from batch are all type 8, although it does mean calling the field for a user on their list who is not type 8 may not be bad.

https://api.skype.com/users/self/contacts/profiles (per above) like pidgin does not throw an error for other types (although does not return any additional information so not super useful).

For the PR I will just assign type 8 for any results from batch as I *believe* it is the only ones it will return.

**Comment by OllieTerrance** [comment]
Err, indeed, misread on my part.  😮  Table updated.

**Comment by himselfv** [comment]
Just a note, plain ```mood``` seems to always be null on ```api.skype.com/users/batch/profiles```, even if it's not null via other means. Maybe there are other fields like that, haven't checked.

**Comment by demurgos** [comment]
Thanks for info.
We now switched to using only the contacts api v2 instead of `users/batch` because the old URL did not work for some users.

@OllieTerrance 
I'd like to better narrow down Skype's HTTP API. I am currently in the process of consolidating info about the conversations API (see the additions to the `types` directory in [this PR](https://github.com/ocilo/skype-http/pull/87/files), I have some sample responses in `test/types`). I also saw that you documented part of the API [on your website](https://skpy.t.allofti.me/protocol/contact.html).
A few years ago I created [a repository to document Skype's HTTP API](https://github.com/demurgos/skype-web-reversed) but in the end the most interesting thing is just the explanation of the LockAndKey computation and a quickly un-bundled version of their JS file.
Would you be interested in having an implementation independent documentation of Skype's API? I could spend some time to document there what I found out by maintaining `skype-http` and give you write access. We'd have to find the best way to do it but it may help both of us by having more data.

I also have a longer-term plan to handle API changes/analysis. I am currently moving to a declarative way to handle Skype's API. This would allow me to generate both a strict and loose data schema. For example in strict mode I could define `mood` to be always `null` while the loose schema and lib API would mark it as `string | null` (either a string or null). I would then always try to use the stricter handler but have a fallback to the loose handler. This would permit invalid assumptions about Skype's API to be warnings instead of errors: the lib remains usable but violation of the hypothesis can be reported. I'd also like to add an easy way to enable HTTP logs or fuzzying of data (change some characters in secrets keys/ids) in my library to facilitate debugging.

**Comment by Terrance** [comment]
> I also saw that you documented part of the API on your website.

https://github.com/OllieTerrance/SkPy.docs/tree/master/protocol holds my HTTP API docs -- they could probably do with being separated from the SkPy library docs.  I'm not sure how up-to-date it is, I haven't poked the Skype APIs in a while now.

Is the idea to generate a schema, and use that to create bindings without the manual effort?

(Fwiw, I'm currently pondering a rewrite of SkPy for asyncio, so maybe I should hold off on that if this goes somewhere...)

**Comment by demurgos** [comment]
Thanks for the link. I'll find some time to look into this more closely.

For the moment I use a Typescript library I wrote myself to support my skype-http use case. For example it has first-class support for discriminated document types (the value of one field such as `messageType` controls the rest of the fields) and supports renames so I can normalize Skype's mess to follow conventional camelCase.
It currently has to be defined in TS code but I was looking into supporting a language independent format such as Protobuf or other. I looked into using Protobuf directly but it was challenging to integrate with Typescript and I did not feel that it was flexible enough to handle an API you don't control.
I am a Python user but mostly for the scientific libraries so I don't really know what are the current best solutions for this use case (schemas, data validation, etc.).

My intent for this first step was to have documentation similar to the Github API v3: types with english free-form description and examples. You'd still have to create the bindings manually but I hope that it'd make it easier. I could also require contributors to `skype-http` to first document their change before sending a PR. If you know a format that you'd be able to use for your Python code, I'd be okay to use it from the beginning as long as its not designed as a Python-only solution.
I'd also like to have generated bindings, but I think that it would require more though and be done in a second step. A good start would be to have easily accessible examples of HTTP responses so they could at least be used for non-regression tests.

Good luck for your rewrite if you decide to go through. I never used `asyncio` but it looks compelling (especially with my Node experience), async usually requires most of the stack to actually be async to benefit from it but it should be fine in SkPy's scope. Beyond the event-based nature and control flow differences, the biggest difference when I compare Node's single threaded cooperative async model and Python's multithreaded sync model is _cancellation_: it's just easier since no thread can get blocked. (The semantics of cancellation can be "don't care about the result" instead of "stop all work".)

**Comment by Terrance** [comment]
> I was looking into supporting a language independent format such as Protobuf or other

I've played with Protobuf in other frameworks (where the underlying platform's APIs use it, e.g. Hangouts) but not tried to write my own schemas with it.  I'm not sure it's the right tool for the job here -- it adds an unnecessary step for crafting/unpacking requests (native <-> Protobuf <-> JSON) when really we just want to validate the responses and use the native conversion.

> I am a Python user but mostly for the scientific libraries so I don't really know what are the current best solutions for this use case (schemas, data validation, etc.)

I've started using [voluptuous](https://pypi.python.org/pypi/voluptuous) in other projects for making assertions about API responses -- you write a schema in relatively plain Python, and then call it on a value to validate.  Particularly nice if the APIs follow a common format, you can write a base schema and extend it for each endpoint -- probably less helpful here though given the variance across Skype's APIs...

> If you know a format that you'd be able to use for your Python code, I'd be okay to use it from the beginning as long as its not designed as a Python-only solution

The docs I have so far are in RST, formatted for [Sphinx's HTTP domain](https://sphinxcontrib-httpdomain.readthedocs.io/en/stable/).  It's not specific to Python, and they don't really help with conversion to bindings or anything, but it's easy enough to express requests.

> async usually requires most of the stack to actually be async to benefit from it

That is exactly my sitation -- I have a larger framework (all async) with which I want to integrate SkPy, meaning I need to convert SkPy to work with it.  🙂  The win for me is running multiple async clients in parallel without having to faff with threads or anything.

**Comment by demurgos** [comment]
I am starting to look into writing my own code-generation tool for schemas. I need it for another project involving Typescript and Rust but I'd also like to make it work here and generate Python code.

It would only generate schema code for serialization/deserialization/validation. I am looking at voluptuous currently. It looks like a good library for validation but I am not sure if it is enough to serialize Skype's messages (rename object keys or more complex behavior such as mixing JSON and XML).
