### ISSUE TITLE
incident library still required

### ISSUE THREAD

**Issue by mitchcapper** [ocilo/skype-http#21]
Had to install incident still as it it still in use ie:  https://github.com/ocilo/skype-http/blob/master/src/lib/connect.ts (and several others).  Just needs to be added back into deps.

I can submit a PR for small items like this or an issue report depending on your preference.

**Comment by demurgos** [comment]
Well, it's embarrassing. I wanted to update it to version 2 but ended up removing it from `package.json`, and it still passed on Travis (build success)...

Feel free to submit PRs for this kind of issues. I'll fix this one and re-publish the package (after checking that importing it works fine).
