### ISSUE TITLE
Drop typings dependency

### ISSUE THREAD

**Issue by mitchcapper** [ocilo/skype-http#23]
```
typings install --save npm:skype-http
typings ERR! message Unable to read typings for "request". The author of "skype-http" needs to check the entry paths in "package.json" are up to date
typings ERR! caused by ENOENT: no such file or directory, open 'C:\temp\skytest\node_modules\skype-http\node_modules\request\index.d.ts\index.d.ts'
typings ERR!
```
I am not a typings expert for how these imports normally  go, it seems it reads from the local folder so not requiring a remote source to be updated. I am guessing it is because request does not have any typings locally.  I am guessing modifying typings.json to specify the npm typings source (not sure why it doesn't pickup from package.json). I can investigate further if the immediate answer is not apparent to someone more familiar.

**Comment by demurgos** [comment]
A better solution would be to completely drop the dependency on typings and only use `@types`. This should simplify the build process and reduce the errors.
