### ISSUE TITLE
[Question]: Is there a way to use something like keytar?

### ISSUE THREAD

**Issue by darkyen** [ocilo/skype-http#44]
Is there a way to use something like keytar so that I don't have to store the user's password in plain text/encrypted?

**Comment by mitchcapper** [comment]
so skype-http does not store the password at all when you pass it in, it is only used to login and get the initial token.  You are welcome to use keytar without issue.

**Comment by darkyen** [comment]
Short answer, Yes. 

Long answer, after `.getState` gets merged to master you can store this the JSON.stringified version of `.getState()` into some secure storage mechanism.
